import type { Metadata } from "next";
import { Vazirmatn } from "next/font/google";
import "./globals.css";

const vazirmatn = Vazirmatn({ subsets: ["latin"] });

import type { Viewport } from 'next'
import Header from "@/components/header/header";

export const viewport: Viewport = {
  themeColor: '#d72685',
}

export const metadata: Metadata = {
  title: "Shavaz",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body className={vazirmatn.className}>
        {/* <Header /> */}
        {children}
      </body>
    </html>
  );
}
